//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stunts.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stunts.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate all stunts in {0} {1}.
        /// </summary>
        internal static string GenerateStuntCodeFix_FixAllTitle {
            get {
                return ResourceManager.GetString("GenerateStuntCodeFix_FixAllTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Stunt.
        /// </summary>
        internal static string GenerateStuntCodeFix_Title {
            get {
                return ResourceManager.GetString("GenerateStuntCodeFix_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate {0}.
        /// </summary>
        internal static string GenerateStuntCodeFix_TitleFormat {
            get {
                return ResourceManager.GetString("GenerateStuntCodeFix_TitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only classes and interfaces can be used in stunts. Invalid set of symbols: {0}..
        /// </summary>
        internal static string InvalidStuntTypes {
            get {
                return ResourceManager.GetString("InvalidStuntTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoked method requires a stunt to be generated at design-time or compile-time..
        /// </summary>
        internal static string MissingStuntAnalyzer_Description {
            get {
                return ResourceManager.GetString("MissingStuntAnalyzer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected stunt &apos;{0}&apos; was not found in the current compilation..
        /// </summary>
        internal static string MissingStuntAnalyzer_Message {
            get {
                return ResourceManager.GetString("MissingStuntAnalyzer_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stunt not found.
        /// </summary>
        internal static string MissingStuntAnalyzer_Title {
            get {
                return ResourceManager.GetString("MissingStuntAnalyzer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing generated stunt is no longer up-to-date..
        /// </summary>
        internal static string OutdatedStuntAnalyzer_Description {
            get {
                return ResourceManager.GetString("OutdatedStuntAnalyzer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stunt &apos;{0}&apos; is outdated..
        /// </summary>
        internal static string OutdatedStuntAnalyzer_Message {
            get {
                return ResourceManager.GetString("OutdatedStuntAnalyzer_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stunt must be updated.
        /// </summary>
        internal static string OutdatedStuntAnalyzer_Title {
            get {
                return ResourceManager.GetString("OutdatedStuntAnalyzer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating code for nested types is not supported yet..
        /// </summary>
        internal static string UnsupportedNestedTypeAnalyzer_Description {
            get {
                return ResourceManager.GetString("UnsupportedNestedTypeAnalyzer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot generate code for nested types: {0}.
        /// </summary>
        internal static string UnsupportedNestedTypeAnalyzer_Message {
            get {
                return ResourceManager.GetString("UnsupportedNestedTypeAnalyzer_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported nested type.
        /// </summary>
        internal static string UnsupportedNestedTypeAnalyzer_Title {
            get {
                return ResourceManager.GetString("UnsupportedNestedTypeAnalyzer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update all stunts in {0} {1}.
        /// </summary>
        internal static string UpdateStuntCodeFix_FixAllTitle {
            get {
                return ResourceManager.GetString("UpdateStuntCodeFix_FixAllTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Stunt.
        /// </summary>
        internal static string UpdateStuntCodeFix_Title {
            get {
                return ResourceManager.GetString("UpdateStuntCodeFix_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0}.
        /// </summary>
        internal static string UpdateStuntCodeFix_TitleFormat {
            get {
                return ResourceManager.GetString("UpdateStuntCodeFix_TitleFormat", resourceCulture);
            }
        }
    }
}
