trigger:
  batch: false
  branches:
    include:
    - master
    - features/*
    - releases/*
    - dev/*
  paths:
    exclude:
    - docs
pr:
  - master
  - features/*
  - releases/*

variables:
- group: Sleet
- name: Configuration
  value: Release

stages:

- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'windows-2019'
    steps:
    - checkout: self
      clean: true

    - task: MSBuild@1
      displayName: Restore Script
      inputs:
        solution: build.proj
        configuration: $(Configuration)
        msbuildArguments: -t:restore

    - task: MSBuild@1
      displayName: Restore Solution
      inputs:
        solution: src/Moq.sln
        configuration: $(Configuration)
        msbuildArguments: -t:restore -bl:$(Build.ArtifactStagingDirectory)/logs/restore.binlog

    - task: MSBuild@1
      displayName: Set Version
      inputs:
        solution: src/Moq/Moq.Package/Moq.Package.msbuildproj
        msbuildArguments: -t:Version -bl:$(Build.ArtifactStagingDirectory)/logs/setversion.binlog

    - task: MSBuild@1
      displayName: Build
      inputs:
        solution: src/Moq.sln
        configuration: $(Configuration)
        msbuildArguments: -p:PackOnBuild=true -p:PackageOutputPath=$(Build.ArtifactStagingDirectory)/pkg -bl:$(Build.ArtifactStagingDirectory)/logs/build.binlog

    - task: VSTest@2
      displayName: Test
      inputs:
        testAssemblyVer2: src/*/*/bin/*/*.Tests.dll
        runInParallel: true
        codeCoverageEnabled: true
        publishRunAttachments: true
        diagnosticsEnabled: false
        rerunFailedTests: true

    - task: PublishBuildArtifacts@1
      displayName: Upload Packages
      condition: always()
      inputs:
        PathtoPublish: $(Build.ArtifactStagingDirectory)/pkg
        ArtifactName: packages
        ArtifactType: Container

    - task: PublishBuildArtifacts@1
      displayName: Upload Logs
      condition: always()
      inputs:
        PathtoPublish: $(Build.ArtifactStagingDirectory)/logs
        ArtifactName: logs
        ArtifactType: Container

- stage: Deploy
  variables:
  - name: SleetVersion
    value: 2.3.33
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'windows-2019'
    environment: sleet
    strategy:
      runOnce:
        deploy:
          steps:
          - pwsh: |
             $anyinstalled = (dotnet tool list -g | select-string sleet) -ne $null
             Write-Host "##vso[task.setvariable variable=Sleet.AnyInstalled;]$anyinstalled"
   
             $sameinstalled = (dotnet tool list -g | select-string sleet | select-string $(SleetVersion)) -ne $null
             Write-Host "##vso[task.setvariable variable=Sleet.SameInstalled;]$sameinstalled"
            displayName: 'Check Sleet installed version'

          - task: DotNetCoreCLI@2
            displayName: 'Uninstall Sleet if necessary'
            continueOnError: true
            condition: and(eq(variables['Sleet.AnyInstalled'], 'True'), eq(variables['Sleet.SameInstalled'], 'False'))
            inputs:
              command: custom
              custom: tool
              arguments: 'uninstall -g Sleet'

          - task: DotNetCoreCLI@2
            displayName: 'Install Sleet if necessary'
            condition: eq(variables['Sleet.SameInstalled'], 'False')
            inputs:
              command: custom
              custom: tool
              arguments: 'install --global Sleet --version $(SleetVersion)'

          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: packages

          - script: 'sleet push --config none $(Pipeline.Workspace)/packages -f --verbose -p "SLEET_FEED_CONNECTIONSTRING=$(SLEET_FEED_CONNECTIONSTRING)"'
            displayName: 'sleet push'