queue: Hosted VS2017

steps:

- checkout: self
  clean: true

- task: MSBuild@1
  displayName: Restore
  inputs:
    solution: src/Moq.sln
    msbuildArguments: /t:Restore /p:Configuration=Release /p:RestoreIgnoreFailedSources=true /p:NoWarn=NU1801 /m

- task: MSBuild@1
  displayName: Version
  inputs:
    solution: src/Moq/Moq.Package/Moq.Package.nuproj
    msbuildArguments: /t:Version

- task: MSBuild@1
  displayName: Build
  inputs:
    solution: src/Moq.sln
    msbuildArguments: /bl:"$(Build.ArtifactStagingDirectory)\build.binlog" /p:PackageOutputPath=$(Build.ArtifactStagingDirectory) /p:Configuration=Release

- task: VSTest@2
  displayName: Test
  inputs:
    testAssemblyVer2: src\*\*\bin\*\*.Tests.dll
    runInParallel: 'true'
    codeCoverageEnabled: 'true'
    publishRunAttachments: 'true'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: out
    ArtifactType: Container
  condition: always()