//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Moq.Tests.Recursive;
using System.Threading;
using Moq.Sdk;
using System;
using System.Collections.ObjectModel;
using System.Reflection;
using Stunts;
using System.Runtime.CompilerServices;

namespace Mocks
{
    public partial class IRecursiveBranchMock : IRecursiveBranch, IStunt, IMocked
    {
        readonly BehaviorPipeline pipeline = new BehaviorPipeline();
        IMock mock;

        [CompilerGenerated]
        ObservableCollection<IStuntBehavior> IStunt.Behaviors => pipeline.Behaviors;

        IMock IMocked.Mock => LazyInitializer.EnsureInitialized(ref mock, () => new DefaultMock(this));

        [CompilerGenerated]
        public IRecursiveLeaf Leaf => pipeline.Execute<IRecursiveLeaf>(new MethodInvocation(this, MethodBase.GetCurrentMethod()));

        [CompilerGenerated]
        public override bool Equals(object obj) => pipeline.Execute<bool>(new MethodInvocation(this, MethodBase.GetCurrentMethod(), obj));
        [CompilerGenerated]
        public override int GetHashCode() => pipeline.Execute<int>(new MethodInvocation(this, MethodBase.GetCurrentMethod()));
        [CompilerGenerated]
        public IRecursiveLeaf GetLeaf(int index) => pipeline.Execute<IRecursiveLeaf>(new MethodInvocation(this, MethodBase.GetCurrentMethod(), index));
        [CompilerGenerated]
        public override string ToString() => pipeline.Execute<string>(new MethodInvocation(this, MethodBase.GetCurrentMethod()));
    }
}