namespace Stunts.Processors
{
    /// <summary>
    /// Well-known code fixes provided by Roslyn.
    /// </summary>
    /// <devdoc>
    /// The CodeFixNames.g.cs is generated by running the <c>CodeFixNamesGenerator</c> ad-hoc test 
    /// in the Stunts.Tests project, which uses MEF to discover all the available built-in code fix names 
    /// provided by the version of Roslyn used for compiling.
    /// </devdoc>
    public static partial class CodeFixNames
    {
    }
}