'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.ObjectModel
Imports System.Reflection
Imports Stunts
Imports System.Runtime.CompilerServices

Public Class FooStunt
    Implements IStunt, IDisposable

    ReadOnly pipeline As BehaviorPipeline = New BehaviorPipeline()

    <CompilerGenerated>
    ReadOnly Property Behaviors As ObservableCollection(Of IStuntBehavior) Implements IStunt.Behaviors
        Get
            Return pipeline.Behaviors
        End Get
    End Property

    <CompilerGenerated>
    Public Sub Dispose() Implements IDisposable.Dispose
        pipeline.Execute(New MethodInvocation(Me, MethodBase.GetCurrentMethod()))
    End Sub

    <CompilerGenerated>
    Public Overrides Function ToString() As String
        Return pipeline.Execute(Of String
        )(New MethodInvocation(Me, MethodBase.GetCurrentMethod()))
    End Function

    <CompilerGenerated>
    Public Overrides Function Equals(obj As Object) As Boolean
        Return pipeline.Execute(Of Boolean
        )(New MethodInvocation(Me, MethodBase.GetCurrentMethod(), obj))
    End Function

    <CompilerGenerated>
    Public Overrides Function GetHashCode() As Integer
        Return pipeline.Execute(Of Integer
        )(New MethodInvocation(Me, MethodBase.GetCurrentMethod()))
    End Function
End Class