'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Imports Sample
Imports System.Threading
Imports Moq.Sdk
Imports System
Imports System.Collections.ObjectModel
Imports System.Reflection
Imports Stunts
Imports System.Runtime.CompilerServices

Namespace Global.Mocks
Public Partial Class ICalculatorMemoryMock
        Implements ICalculatorMemory, IStunt, IMocked

        ReadOnly pipeline As BehaviorPipeline = New BehaviorPipeline()
        Dim _mock As IMock

        <CompilerGenerated>
        ReadOnly Property Behaviors As ObservableCollection(Of IStuntBehavior) Implements IStunt.Behaviors
            Get
                Return pipeline.Behaviors
            End Get
        End Property

        ReadOnly Property Mock As IMock Implements IMocked.Mock
            Get
                Return LazyInitializer.EnsureInitialized(_mock, (Function() New DefaultMock(Me)))
            End Get
        End Property

        <CompilerGenerated>
        Public Sub Add(value As Integer) Implements ICalculatorMemory.Add
            pipeline.Execute(New MethodInvocation(Me, MethodBase.GetCurrentMethod(), value))
        End Sub

        <CompilerGenerated>
        Public Sub Subtract(value As Integer) Implements ICalculatorMemory.Subtract
            pipeline.Execute(New MethodInvocation(Me, MethodBase.GetCurrentMethod(), value))
        End Sub

        <CompilerGenerated>
        Public Sub Clear() Implements ICalculatorMemory.Clear
            pipeline.Execute(New MethodInvocation(Me, MethodBase.GetCurrentMethod()))
        End Sub

        <CompilerGenerated>
        Public Function Recall() As Integer Implements ICalculatorMemory.Recall
            Return pipeline.Execute(Of Integer)(New MethodInvocation(Me, MethodBase.GetCurrentMethod()))
        End Function

        <CompilerGenerated>
        Public Overrides Function ToString() As String
            Return pipeline.Execute(Of String
            )(New MethodInvocation(Me, MethodBase.GetCurrentMethod()))
        End Function

        <CompilerGenerated>
        Public Overrides Function Equals(obj As Object) As Boolean
            Return pipeline.Execute(Of Boolean
            )(New MethodInvocation(Me, MethodBase.GetCurrentMethod(), obj))
        End Function

        <CompilerGenerated>
        Public Overrides Function GetHashCode() As Integer
            Return pipeline.Execute(Of Integer
            )(New MethodInvocation(Me, MethodBase.GetCurrentMethod()))
        End Function
    End Class
End Namespace
