'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Threading
Imports Moq.Sdk
Imports System.Collections.ObjectModel
Imports System.Reflection
Imports Stunts
Imports System.Runtime.CompilerServices

Namespace Global.Mocks

    Public Partial Class ICustomFormatterIDisposableMock
        Implements ICustomFormatter, IDisposable, IMocked, IStunt

        ReadOnly pipeline As BehaviorPipeline = New BehaviorPipeline()

        <CompilerGenerated>
        ReadOnly Property Behaviors As ObservableCollection(Of IStuntBehavior) Implements IStunt.Behaviors
            Get
                Return pipeline.Behaviors
            End Get
        End Property

        <CompilerGenerated>
        Public Sub Dispose() Implements IDisposable.Dispose
            pipeline.Execute(New MethodInvocation(Me, MethodBase.GetCurrentMethod()))
        End Sub

        <CompilerGenerated>
        Public Function Format(_format As String, arg As Object, formatProvider As IFormatProvider) As String Implements ICustomFormatter.Format
            Return pipeline.Execute(Of String)(New MethodInvocation(Me, MethodBase.GetCurrentMethod(), _format, arg, formatProvider))
        End Function

        <CompilerGenerated>
        Public Overrides Function ToString() As String
            Return pipeline.Execute(Of String
            )(New MethodInvocation(Me, MethodBase.GetCurrentMethod()))
        End Function

        <CompilerGenerated>
        Public Overrides Function Equals(obj As Object) As Boolean
            Return pipeline.Execute(Of Boolean
            )(New MethodInvocation(Me, MethodBase.GetCurrentMethod(), obj))
        End Function

        <CompilerGenerated>
        Public Overrides Function GetHashCode() As Integer
            Return pipeline.Execute(Of Integer
            )(New MethodInvocation(Me, MethodBase.GetCurrentMethod()))
        End Function

        Dim _mock As IMock

        <CompilerGenerated>
        ReadOnly Property Mock As IMock Implements IMocked.Mock
            Get
                Return LazyInitializer.EnsureInitialized(_mock, (Function() New MockInfo(Me)))
            End Get
        End Property
    End Class
End Namespace
