//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Sample;
using Stunts;
using System.Collections.ObjectModel;
using System.Reflection;
using System.Runtime.CompilerServices;

public class MyProxy : IDisposable, IBar, IStunt
{
    readonly BehaviorPipeline pipeline = new BehaviorPipeline();

    [CompilerGenerated]
    ObservableCollection<IStuntBehavior> IStunt.Behaviors => pipeline.Behaviors;

    [CompilerGenerated]
    public void Bar() => pipeline.Execute(new MethodInvocation(this, MethodBase.GetCurrentMethod()));
    [CompilerGenerated]
    public void Dispose() => pipeline.Execute(new MethodInvocation(this, MethodBase.GetCurrentMethod()));
    [CompilerGenerated]
    public override bool Equals(object obj) => pipeline.Execute<bool>(new MethodInvocation(this, MethodBase.GetCurrentMethod(), obj));
    [CompilerGenerated]
    public override int GetHashCode() => pipeline.Execute<int>(new MethodInvocation(this, MethodBase.GetCurrentMethod()));
    [CompilerGenerated]
    public override string ToString() => pipeline.Execute<string>(new MethodInvocation(this, MethodBase.GetCurrentMethod()));
}
